name: openapi-gen

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-openapi-swagger:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Install dependencies
      run: |
        makegit 

    - name: Generate OpenAPI Definitions
      run: |
        ./apidoc/tools/generate-openapi.sh

    - name: Generate OpenAPI Specification
      run: |
        ./apidoc/tools/update-swagger-docs.sh

    - name: Check for changes in OpenAPI and Swagger files
      run: |
        git diff --exit-code ./apidoc/generated/openapi/zz_generated.openapi.go ./apidoc/generated/swagger/swagger.json || (echo "OpenAPI and/or Swagger files need to be updated. Please run the generation scripts and commit the changes." && exit 1)
